// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAOXuIzQtKjUnHRVWCP9YG0dBSoKdQsUJE',
    appId: '1:31525880052:web:1b42e3812040594698dea1',
    messagingSenderId: '31525880052',
    projectId: 'memoaura',
    authDomain: 'memoaura.firebaseapp.com',
    storageBucket: 'memoaura.firebasestorage.app',
    measurementId: 'G-J1LK4HXBBP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCM4GnnFiO_CqhzwXmw2kVmydzRNcr9r_8',
    appId: '1:31525880052:android:22b98a76b3638f3198dea1',
    messagingSenderId: '31525880052',
    projectId: 'memoaura',
    storageBucket: 'memoaura.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCXz2adGobfo0qnnvTYzbE-wojZFl9scIg',
    appId: '1:31525880052:ios:53aabadd73f8815b98dea1',
    messagingSenderId: '31525880052',
    projectId: 'memoaura',
    storageBucket: 'memoaura.firebasestorage.app',
    iosBundleId: 'com.example.memoaura',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCXz2adGobfo0qnnvTYzbE-wojZFl9scIg',
    appId: '1:31525880052:ios:53aabadd73f8815b98dea1',
    messagingSenderId: '31525880052',
    projectId: 'memoaura',
    storageBucket: 'memoaura.firebasestorage.app',
    iosBundleId: 'com.example.memoaura',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAOXuIzQtKjUnHRVWCP9YG0dBSoKdQsUJE',
    appId: '1:31525880052:web:e097097e7f1ddb6098dea1',
    messagingSenderId: '31525880052',
    projectId: 'memoaura',
    authDomain: 'memoaura.firebaseapp.com',
    storageBucket: 'memoaura.firebasestorage.app',
    measurementId: 'G-4NY6CYM84T',
  );
}
